- request:
    url: /disco/api/account
    method: get
    query:
      clientId: 6d1ea72d-8173-4aa2-b0f4-7cd574c5d24c
  response:
    - status: 200
      latency: 500
      headers:
        content-type: application/json
      file: ./account/get-all-200.json
